# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa1f84aab0b34e3a616f974e90087194c0a9c9f7d1b0abc23809732be308f3c2dfabca03c36ed2ecb123709141874646f983ef13049967a7c97bb8718ded31a3

test:
  secret_key_base: 400ccb78348b35f0209ccd00678b125030e19c32e189c0c3673681d839e442e8bcce828724447453ebb572f7c4debc319010acccc1fb45935d5d942aa5c40f57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
